/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// PA5 = LED GREEN

#include "stm32g0b1xx.h"
#include <stdint.h>
#include "gpio.h"
#include "rcc.h"
#include "usart.h"
#include "timer.h"


void delay_(){
 volatile int i = 0;
 while (i<=1600000) {
   i++;
 }
}


int main(void)
{
	SetSystemClockTo16Mhz();
	UART2_innit();
	//configureTimer2();

	// ON BOARD GREEN LED ENABLE
	RCC->IOPENR = RCC_IOPENR_GPIOAEN; // ENABLE CLOCK ACCESS TO GPIO A
	// Pin A5 Output (Onboard Green LED)
	GPIOA->MODER |=(1U<<10);  // SET BIT 10 to 1
	GPIOA->MODER &=~(1U<<11);  // SET BIT 11 to 0

	while(1)
	{
 		 //Set the 5th bit of Port A5
  		 GPIOA->BSRR |= GPIO_BSRR_BS5;
		 delay_(); // 1 Second Delay
		//reset the 5th bit of Port A5
		 GPIOA->BSRR |= GPIO_BSRR_BR5;
		 delay_(); // 1 Second Delay
	     UART2_send("testing 123",sizeof"testing 123");
	 	}

}
